Eindproject/Controllers/AdministrationController.cs
using Eindproject.Data;
using Eindproject.Domain;
using Eindproject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eindproject.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        //[Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            var vm = new RoleCreateViewModel
            {
                Users = Userlist(),
                UserRoles = UserRoles()
            };
            return View(vm);
        }

        [HttpPost] 
        public async Task<IActionResult> Create(RoleCreateViewModel vm)
        {
            if (TryValidateModel(vm))
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = vm.Name,

                };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("create", "administration");
                }
            }

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> AddUserRole(RoleCreateViewModel vm)
        {          
            var user = userManager.Users.FirstOrDefault(u => u.Id == vm.UserId);

            var roleName = roleManager.Roles.FirstOrDefault(u => u.Id == vm.UserRoleId).Name;

            await userManager.AddToRoleAsync(user, roleName);
            
            return RedirectToAction("create", "administration");
        }
        private List<SelectListItem> Userlist()
        {
            List<SelectListItem> list = new List<SelectListItem>();

            foreach (var item in userManager.Users)
            {
                list.Add(new SelectListItem { Value = item.Id, Text = item.UserName });
            }

            return list;
        }
        private List<SelectListItem> UserRoles()
        {

            List<SelectListItem> list = new List<SelectListItem>();

            foreach (var item in roleManager.Roles)
            {
                list.Add(new SelectListItem { Value = item.Id, Text = item.Name });
            }

            return list;
        }
    }
}

Eindproject/Views/Administration/Create.cshtml
@model RoleCreateViewModel

<h1>Create a new role</h1>
@*
Dit is de code voor een roll te createn

<form asp-controller="Administration" asp-action="Create" method="Post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

*@



<form asp-controller="Administration" asp-action="AddUserRole" method="Post">
    <div class="form-group">
        <label asp-for="UserRoleId">UserRole</label>
        <select class="form-control" asp-items="ViewData.Model.UserRoles" asp-for="UserRoleId"></select>
        <span class="text-danger" asp-validation-for="UserRoleId"></span>
    </div>
    <div class="form-group">
        <label asp-for="UserId">User</label>
        <select class="form-control" asp-items="ViewData.Model.Users" asp-for="UserId"></select>
        <span class="text-danger" asp-validation-for="UserId"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>